---
- name: Devices OSPF configuration
  hosts: devices
  gather_facts: false

  tasks:
    - name: OSPF config
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              networks:
                - area: 0.0.0.0
                  prefix: 10.0.0.0/16
