---
- name: Check for routes
  hosts: leaf1
  gather_facts: false

  tasks:
    - name: Query or base
      block:
        - name: Query routing table
          arista.eos.eos_command:
            commands:
              - show ip route
            wait_for:
              - result[0] contains '10.0.13.0/30'
      rescue:
        - name: When failed
          arista.eos.eos_config:
            lines:
              - configure replace flash:base.cfg
