- name: Leaf2 IP configuration
  hosts: leaf2
  gather_facts: false
  
  tasks:
    - name: Loopback
      arista.eos.eos_l3_interfaces:
        config:
          - name: Loopback0
            ipv4:
            - address: 10.0.200.1/32
        state: replaced
    - name: no switchport
      arista.eos.eos_interfaces:
        config:
          - name: Ethernet1
            mode: layer3
        state: replaced
    - name: ip_Et1   
      arista.eos.eos_l3_interfaces:
        config:
          - name: Ethernet1
            ipv4:
            - address: 10.0.10.2/30
        state: replaced
    - name: ospf   
      arista.eos.eos_ospfv2:
        config:
         processes: 
           - process_id: 1
             networks: 
              - area: "0.0.0.0"
                prefix: "10.0.10.1/24"
                prefix: "10.0.200.1/32"
    - name: bgp           
      arista.eos.eos_bgp_global:
        config:
           as_number: "65000" 
           neighbor: 
            - neighbor_address: "10.0.100.1"
              update_source: "Loopback0" 
              remote_as: "65000"